apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testcd-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.petw.world/
    targetRevision: 0.0.*
    chart: testcd
    helm:
      releaseName: testcd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  destination:
    server: https://kubernetes.default.svc
    namespace: testcd
